################################################################################
## R script for functions in OptHoldoutSize package                           ##
################################################################################
##
## Sami Haidar-Wehbe, Sam Emerson, James Liley
## October 2021
##

## TODO: vignette:
##  Use simulated data: generation, estimation, etc
##  Note that confidence interval with non-normal estimators of pars can be
##   generated by simulating from a non-normal distribution


################################################################################
## Packages and scripts                                                       ##
################################################################################

require("matrixStats")  # Matrix row- and column-wise operations
require("mnormt")       # Multivariate normal distributions
require("mvtnorm")      # Multivariate normal and t distributions
require("dplyr")        # Syntax
require("ranger")       # Random forests
require("mle.tools")    # Gaussian processes

################################################################################
## Small auxiliary functions                                                  ##
################################################################################

## These functions are not annotated.

logit=function(x) 1/(1+exp(-x))
logistic=function(x) -log((1/x)-1)

